# CMake generated Testfile for 
# Source directory: /workspace/Tests/AetherisRendering
# Build directory: /workspace/build-standalone/Tests/AetherisRendering
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[AetherisHtmlTokenizer]=] "/workspace/build-standalone/bin/TestAetherisHtmlTokenizer")
set_tests_properties([=[AetherisHtmlTokenizer]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;5;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisDomBuilder]=] "/workspace/build-standalone/bin/TestAetherisDomBuilder")
set_tests_properties([=[AetherisDomBuilder]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;11;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisCss]=] "/workspace/build-standalone/bin/TestAetherisCss")
set_tests_properties([=[AetherisCss]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;17;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisCascade]=] "/workspace/build-standalone/bin/TestAetherisCascade")
set_tests_properties([=[AetherisCascade]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;23;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisLayout]=] "/workspace/build-standalone/bin/TestAetherisLayout")
set_tests_properties([=[AetherisLayout]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;29;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisBoxModel]=] "/workspace/build-standalone/bin/TestAetherisBoxModel")
set_tests_properties([=[AetherisBoxModel]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;35;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisTextLayout]=] "/workspace/build-standalone/bin/TestAetherisTextLayout")
set_tests_properties([=[AetherisTextLayout]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;42;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisPaintBackend]=] "/workspace/build-standalone/bin/TestAetherisPaintBackend")
set_tests_properties([=[AetherisPaintBackend]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;49;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisPaintEffects]=] "/workspace/build-standalone/bin/TestAetherisPaintEffects")
set_tests_properties([=[AetherisPaintEffects]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;56;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisAdvancedLayout]=] "/workspace/build-standalone/bin/TestAetherisAdvancedLayout")
set_tests_properties([=[AetherisAdvancedLayout]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;63;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisAdvancedPainting]=] "/workspace/build-standalone/bin/TestAetherisAdvancedPainting")
set_tests_properties([=[AetherisAdvancedPainting]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;69;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisResourcesImages]=] "/workspace/build-standalone/bin/TestAetherisResourcesImages")
set_tests_properties([=[AetherisResourcesImages]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;73;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisTypographyResources]=] "/workspace/build-standalone/bin/TestAetherisTypographyResources")
set_tests_properties([=[AetherisTypographyResources]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;77;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisAdvancedVisuals]=] "/workspace/build-standalone/bin/TestAetherisAdvancedVisuals")
set_tests_properties([=[AetherisAdvancedVisuals]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;81;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisStackingOverflow]=] "/workspace/build-standalone/bin/TestAetherisStackingOverflow")
set_tests_properties([=[AetherisStackingOverflow]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;85;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisBackgroundTiling]=] "/workspace/build-standalone/bin/TestAetherisBackgroundTiling")
set_tests_properties([=[AetherisBackgroundTiling]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;89;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisFlexLayout]=] "/workspace/build-standalone/bin/TestAetherisFlexLayout")
set_tests_properties([=[AetherisFlexLayout]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;93;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisGridLayout]=] "/workspace/build-standalone/bin/TestAetherisGridLayout")
set_tests_properties([=[AetherisGridLayout]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;97;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisAdvancedFlexLayout]=] "/workspace/build-standalone/bin/TestAetherisAdvancedFlexLayout")
set_tests_properties([=[AetherisAdvancedFlexLayout]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;101;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisAdvancedSizing]=] "/workspace/build-standalone/bin/TestAetherisAdvancedSizing")
set_tests_properties([=[AetherisAdvancedSizing]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;105;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisTypography]=] "/workspace/build-standalone/bin/TestTypography")
set_tests_properties([=[AetherisTypography]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;109;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisWhitespace]=] "/workspace/build-standalone/bin/TestWhitespace")
set_tests_properties([=[AetherisWhitespace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;113;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisTextAlignment]=] "/workspace/build-standalone/bin/TestTextAlignment")
set_tests_properties([=[AetherisTextAlignment]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;117;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisTextDecoration]=] "/workspace/build-standalone/bin/TestTextDecoration")
set_tests_properties([=[AetherisTextDecoration]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;121;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisDocumentResources]=] "/workspace/build-standalone/bin/TestAetherisDocumentResources")
set_tests_properties([=[AetherisDocumentResources]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;125;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisNavigation]=] "/workspace/build-standalone/bin/TestAetherisNavigation")
set_tests_properties([=[AetherisNavigation]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;129;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisResourceLoader]=] "/workspace/build-standalone/bin/TestAetherisResourceLoader")
set_tests_properties([=[AetherisResourceLoader]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;133;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisResourceBackends]=] "/workspace/build-standalone/bin/TestAetherisResourceBackends")
set_tests_properties([=[AetherisResourceBackends]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;137;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisPageLifecycle]=] "/workspace/build-standalone/bin/TestAetherisPageLifecycle")
set_tests_properties([=[AetherisPageLifecycle]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;141;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisFormRuntime]=] "/workspace/build-standalone/bin/TestAetherisFormRuntime")
set_tests_properties([=[AetherisFormRuntime]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;145;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisVisualInteraction]=] "/workspace/build-standalone/bin/TestAetherisVisualInteraction")
set_tests_properties([=[AetherisVisualInteraction]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;149;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisRuntimeStyles]=] "/workspace/build-standalone/bin/TestAetherisRuntimeStyles")
set_tests_properties([=[AetherisRuntimeStyles]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;153;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[TestBrowserApplication]=] "/workspace/build-standalone/bin/TestBrowserApplication")
set_tests_properties([=[TestBrowserApplication]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;157;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisDynamicRuntime]=] "/workspace/build-standalone/bin/TestAetherisDynamicRuntime")
set_tests_properties([=[AetherisDynamicRuntime]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;161;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisHttpState]=] "/workspace/build-standalone/bin/TestAetherisHttpState")
set_tests_properties([=[AetherisHttpState]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;165;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisSecurityPolicy]=] "/workspace/build-standalone/bin/TestAetherisSecurityPolicy")
set_tests_properties([=[AetherisSecurityPolicy]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;169;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisSecurityIntegration]=] "/workspace/build-standalone/bin/TestAetherisSecurityIntegration")
set_tests_properties([=[AetherisSecurityIntegration]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;173;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[TestBrowserChrome]=] "/workspace/build-standalone/bin/TestBrowserChrome")
set_tests_properties([=[TestBrowserChrome]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;179;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
add_test([=[AetherisReleaseSmoke]=] "/workspace/build-standalone/bin/TestAetherisReleaseSmoke")
set_tests_properties([=[AetherisReleaseSmoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Tests/AetherisRendering/CMakeLists.txt;183;add_test;/workspace/Tests/AetherisRendering/CMakeLists.txt;0;")
